### ISSUE TITLE
JAFFA format support

### ISSUE THREAD

**Issue by NoeGeno** [yhoogstrate/fuma#20]
Dear yhoogstrate, 
Thanks for you nice and usefull program. It helps me a lot to compare all results from fusion algorithms. 
It would be great to have JAFFA format support. There is a description here: https://github.com/Oshlack/JAFFA/wiki/OutputDescription.
The output file is jaffa_results.csv.

I attach to this message an exemple of output file (result of the example from JAFFA).

Thank you ! 
Best regards, 

[jaffa_results.csv.txt](https://github.com/yhoogstrate/fuma/files/151015/jaffa_results.csv.txt)

Noemie

**Comment by yhoogstrate** [comment]
Hey @NoeGeno,

I don't know why I didn't see your issue on GitHub before, but now I do so I will look into this a.s.a.p.! Thanks for reporting :)

**Comment by yhoogstrate** [comment]
Dear @NoeGeno I have implemented JAFFA as you requested (https://github.com/yhoogstrate/fuma/commit/e4c63ca0b6c6d9719e574e5df64177492772c666, https://github.com/yhoogstrate/fuma/releases/tag/v2.11.6). I want to emphasize that on their website they say _Note that these are ordered by position and not by transcriptional direction._ and therefore I have disabled `acceptor-donor-specific-order` for that particular type of files. Also the output format doesn't provide any strands so I have also disabled `strand-specific-matching` for JAFFA files. The manual isn't clear about the positions are 0-based or 1-based. I have chosen to use 0-based. Although the impact of the last decision is marginal it is important to let you know.

Thanks again for reporting this and if you have any more suggestions or remarks, don't hazitate and create an issue. If JAFFA format is not working as expected, please re-open this issue and tell me what's wrong.
