### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by bow** [yhoogstrate/fuma#35]
Hi @yhoogstrate,

I was wondering if there are any plans on porting this to make it at least Python 3 compatible? I'm planning to use this in a soon-to-be released pipeline, but a portion of the pipeline that uses Python is on Python 3.

If you need help, I can also take a look :).

**Comment by yhoogstrate** [comment]
Hey @bow, thanks! I've been struggling with the same issue, but I'm stuck because HTSeq is not python3 compatible: https://github.com/simon-anders/htseq/pull/9 - If you can help me on that, we're pretty close to having FuMa in Py3

b.t.w conda has a very useful tool for conversion called `2to3`.

**Comment by yhoogstrate** [comment]
It seems there will be no version of HTSeq dat will be compatible with both python2 and python3 and I am not considering porting it to python3 with losing compatibilty with python2.
