### ISSUE TITLE
FusionCatcher Error

### ISSUE THREAD

**Issue by KeyTals** [yhoogstrate/fuma#39]
Hi,

I am trying to run fuma with fusion catcher and i am getting the following error. Could you plea help me to solve this error (my guess is stupid mistake from my side)

Command

 /opt/nasapps/development/fuma/3.0.3/bin/fuma -s "fusioncatcher:fusion-catcher_final:final_list_candidate-fusion-genes.txt" "ericscript:ericscript:ES.results.filtered.tsv" -f "list"  --strand-specific-matching --acceptor-donor-order-specific-matching -o "fuma.txt" -l "FusionCatcher:hg38" "ericscript:hg38"

Error

Traceback (most recent call last):
  File "/opt/nasapps/development/fuma/3.0.3/bin/fuma", line 4, in <module>
    __import__('pkg_resources').run_script('fuma==3.0.3', 'fuma')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 724, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1656, in run_script
  File "/opt/nasapps/development/fuma/3.0.3/lib/python2.7/site-packages/fuma-3.0.3-py2.7.egg/EGG-INFO/scripts/fuma", line 203, in <module>

Exception: unknown sample: FusionCatcher

Thanks,
Keyur

**Comment by yhoogstrate** [comment]
I think it's case sensitive. What happens if you run:


fuma -s "**FusionCatcher**:fusion-catcher_final:final_list_candidate-fusion-genes.txt" "ericscript:ericscript:ES.results.filtered.tsv" -f "list" --strand-specific-matching --acceptor-donor-order-specific-matching -o "fuma.txt" -l "**FusionCatcher**:hg38" "ericscript:hg38"

**Comment by KeyTals** [comment]
Now it works with “FusionCatcher”.

Thanks,
Keyur

**Comment by yhoogstrate** [comment]
Fantastic! Would you llike to close the issue? Thanks for reporting it here 👍 ,

Youri
