### ISSUE TITLE
Pizzly support

### ISSUE THREAD

**Issue by mblue9** [yhoogstrate/fuma#41]
Hi Youri,

As you suggested in IUC Gitter, I'm creating an issue to request FuMa support for Pizzly input.

Attached is an example of Pizzly output.

Thanks a lot!

Maria

[out.fusions.tab.txt](https://github.com/yhoogstrate/fuma/files/1304979/out.fusions.tab.txt)

**Comment by mblue9** [comment]
Pizzly also outputs a fasta file, example attached here.
[out.fusions.fasta.txt](https://github.com/yhoogstrate/fuma/files/1304984/out.fusions.fasta.txt)

**Comment by yhoogstrate** [comment]
Hi Maria,

This is going to be hard as it does not provide genomic locations.. That's the input FuMa needs. Do you use random hexamer or poly-A RNA-seq data?
